name: Build

on: 
  push:
    branches:
      - master

jobs:

  build:

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      SOLUTION_PATH: 'Blockcore.SampleCoin/Blockcore.SampleCoin.sln'
      BUILD_CONFIGURATION: 'Release'
    
    steps:
      
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      
    - name: Restore
      run: dotnet restore ${{env.SOLUTION_PATH}}

    - name: Build
      run: dotnet build --configuration ${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_PATH}} --no-restore
